name: Deploy to Firebase Hosting on merge
on: pull_request
jobs:
  build:
    name: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build and export
        run: yarn next build && yarn next export
        env:
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}

      - name: Deploy
        run: yarn deploy:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
